---
pagetitle: "Research | OMICS Center"
toc: true
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Research</li>
  </ol>
</nav>
```

## Research Topics

### RNA-Seq

- **The Introduction of RNA-Seq** – RNA-Seq is the premier tool for mapping and quantifying transcriptomes by utilizing next-generation sequencing (NGS) technology. The transcriptome refers to the complete set of transcripts in a cell, which provides information on the transcript level for a specific developmental stage or physiological condition. Understanding the transcriptome is necessary for interpreting the functional elements of the genome and understanding development and disease. The key purpose of transcriptomics includes cataloging all species of transcripts; determining the transcriptional structure of genes; and quantifying the expression levels of each transcript under different conditions.

RNA-Seq delivers an unbiased and unprecedented high-resolution view of the global transcriptional landscape, which allows an affordable and accurate approach for gene expression quantification and differential gene expression analysis between multiple groups of samples. RNA-Seq can identify novel and previously-unexpected transcripts without the need for a reference genome, allowing de novo assembly of new transcriptome that is not previously studied before. It also enables the discovery of novel gene structures, alternatively spliced isoforms, gene fusions, SNPs/InDel, and allele-specific expression (ASE).

- **Advantages of RNA-Seq** – 
  - Quantitative and precise measurements of RNA molecules at a single base-pair resolution
  - Discovery of novel transcripts, splice variants, and gene fusions
  - Application to any species, no matter whether reference genome is available
  - A comparable or lower price than many other methods


